development:
  adapter: postgresql
  encoding: unicode
  database: wld_dev
  pool: 5
  host: localhost
  username: wld
  password: t1734l2112OC2305!r

test:
  adapter: postgresql
  encoding: unicode
  database: wld_test
  pool: 5
  host: localhost
  username: wld
  password: t1734l2112OC2305!r
